[package]
name = "snake_game_rust"
version = "0.1.2"
edition = "2021"
authors = ["Lorenzo Leonardo <enzotechcomputersolutions@gmail.com>"]

[dependencies]
rand = "0.8"
crossterm = "0.27"
tokio = { version = "1.38", features = ["rt", "rt-multi-thread", "test-util", "macros", "time"] }